### ISSUE TITLE
Fails to skip invalid rule

### ISSUE THREAD

**Issue by Ali-00-Ridha** [0xVavaldi/ruleprocessorY#4] opened 2023-06-15 21:27 UTC
read the rule (Sa4) as a valid rule where the valid one should be with lower s (sa4). this invalid rules exists in InsidePro-HashManager.rule file that cames in hashcat rules folder.

this is my command I used to clean my file that contain this and similar rules that start with S:
[ruleprocessorY.exe --optimize-no-op -r ".\input.rule" --hashcat-input --hashcat-output > ruleprocessorY_out.rule]

**Comment by 0xVavaldi** [comment] 2023-06-15 23:02
It marks the Sa4 rule as valid because the S rule exists as a custom rule in ruleprocessorY.
The S rule will perform the same operation as 's' except that it will do so on the 'first occurrence' of a string instead of all.

This means that only the first a will be replaced by 4 in your example, instead of all a's.

**Comment by 0xVavaldi** [comment] 2023-06-15 23:03
I realize this might not be your expected behaviour so feel free to add on if you have any questions / remarks and otherwise close the issue.

**Comment by Ali-00-Ridha** [comment] 2023-06-15 23:15
Yes, I expected that the rule should be removed/converted because I used [--hashcat-input --hashcat-output] in my command which should mean to (read and output) only hashcat valid rules OR convert input rules into valid hashcat rules in output file.
Or maybe I'm not understanding the command!.

**Comment by 0xVavaldi** [comment] 2023-07-03 13:23
The above commit should resovle this issue.

**Comment by 0xVavaldi** [comment] 2023-07-14 22:06
> The above commit should resolve this issue.

Seeing the thumbs up, I'll take it as resolved. Closing the issue.

**Closed by 0xVavaldi** 2023-07-14 22:06 UTC
